name: 在最新Ubuntu上运行脚本并循环Ping

on:
  workflow_dispatch:

jobs:
  run-on-ubuntu:
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载并运行脚本
        run: curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh

      - name: 循环 Ping Google
        run: |
          echo "开始持续 ping baidu.com (每隔 1 分钟一次)"
          while true; do
            ping -c 1 baidu.com
            sleep 60
          done
        shell: bash
