- name: 连接到 OpenVPN
        run: |
          #!/bin/bash
          set -eux

          echo "--- 开始连接 OpenVPN ---"

          OPENVPN_CONFIG_CONTENT="${{ secrets.OPENVPN_CONFIG }}"
          CONFIG_DIR="/etc/openvpn/client"

          echo "安装 OpenVPN 软件包..."
          if ! dpkg -s openvpn > /dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y openvpn
          else
            echo "OpenVPN 软件包已安装."
          fi

          echo "创建配置目录: ${CONFIG_DIR}"
          sudo mkdir -p "${CONFIG_DIR}"
          sudo chmod 700 "${CONFIG_DIR}"

          echo "创建 OpenVPN 配置文件: ${CONFIG_DIR}/client.conf (从 Secret)"
          cat <<EOF | sudo tee "${CONFIG_DIR}/client.conf" > /dev/null
          ${OPENVPN_CONFIG_CONTENT}
          EOF
          sudo chmod 600 "${CONFIG_DIR}/client.conf"

          echo "启动 OpenVPN 客户端 (显示所有日志)..."
          # 移除 --daemon 和 --log 参数，将日志输出到控制台
          sudo openvpn --config "${CONFIG_DIR}/client.conf" --writepid /tmp/openvpn.pid || {
            echo "✗ OpenVPN 客户端启动失败."
            exit 1
          }

          echo "等待 OpenVPN 连接建立 (更长时间)..."
          sleep 20

          echo "验证 OpenVPN 连接..."
          TIMEOUT=60
          VPN_IFACE="tunx"

          while [ "$TIMEOUT" -gt 0 ]; do
            if ip addr show "${VPN_IFACE}" > /dev/null 2>&1 && ip addr show "${VPN_IFACE}" | grep "inet " > /dev/null; then
              echo "${VPN_IFACE} 接口找到并已分配 IP 地址!"
              DEFAULT_ROUTE=$(ip route show default)
              if echo "$DEFAULT_ROUTE" | grep "${VPN_IFACE}"; then
                echo "✓ VPN 连接成功，默认路由通过 ${VPN_IFACE}."
                ip addr show "${VPN_IFACE}"
                ip route show
                break
              else
                echo "${VPN_IFACE} 接口存在并有 IP，但默认路由未通过 VPN:"
                ip route show
              fi
            else
              echo "等待 ${VPN_IFACE} 接口并获取 IP 地址... 剩余 ${TIMEOUT} 秒"
            fi
            sleep 10
            TIMEOUT=$((TIMEOUT - 10))
          done

          if ! ip addr show "${VPN_IFACE}" > /dev/null 2>&1 || ! ip route show default | grep "${VPN_IFACE}"; then
            echo "✗ OpenVPN 连接失败或未建立默认路由。"
            echo "=== Route Table ==="
            ip route show
            echo "=== IP Addr ==="
            ip addr show
            echo "==================="
            if [ -f "/tmp/openvpn.pid" ]; then
              sudo kill "$(cat /tmp/openvpn.pid)" || true
            fi
            exit 1
          fi

          echo "--- OpenVPN 连接步骤完成 ---"

      # --- 原有的下载并运行脚本步骤 ---
      - name: 下载并运行脚本
        run: curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh

      # --- 原有的循环检查网络连接步骤 ---
      - name: 循环检查网络连接和状态
        run: |
          #!/bin/bash

          echo "开始持续检查网络连接 (每隔 1 分钟一次)"

          while true; do
            echo "--- 检查开始 $(date) ---"

            # ... (你的网络检查代码) ...

            echo "--- 检查结束 ---"
            sleep 60
          done
        shell: bash
