name: Run Script on Ubuntu Latest with Delay

on:
  workflow_dispatch: # 保留手动触发

jobs:
  run-on-ubuntu:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu GitHub 托管 runner

    steps:
      - name: Checkout Code # 检出代码
        uses: actions/checkout@v4

      - name: Download and Run Script # 下载并执行您的脚本
        run: curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh

      # 添加一个步骤，暂停 Job 10 分钟 (600 秒)
      - name: Wait for Observation
        run: sleep 600 # 等待 600 秒 (10 分钟)
        shell: bash # 明确指定使用 bash 来执行 sleep 命令

      - name: This step runs after delay
        run: echo "Delay ended, job finishing up."
