name: 在最新Ubuntu上运行脚本并循环检查网络

on:
  workflow_dispatch:

jobs:
  run-on-ubuntu:
    runs-on: ubuntu-latest

    timeout-minutes: 60

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 下载并运行脚本
        run: curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh

      - name: 循环检查网络连接和状态
        run: |
          #!/bin/bash

          echo "开始持续检查网络连接 (每隔 1 分钟一次)"

          while true; do
            echo "--- 检查开始 $(date) ---"

            GOOGLE_STATUS=""
            BAIDU_STATUS=""

            GOOGLE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -m 10 -L https://www.google.com)

            if [ "$GOOGLE_STATUS" == "200" ]; then
              echo "√ Google 连接成功并响应 200 OK"
            else
              echo "x Google 连接失败或非 200 响应 (状态码: $GOOGLE_STATUS)。尝试检查 Baidu..."
              
              BAIDU_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -m 10 -L https://www.baidu.com)

              if [ "$BAIDU_STATUS" == "200" ]; then
                echo "√ Baidu 连接成功并响应 200 OK"
              else
                echo "x Baidu 连接失败或非 200 响应 (状态码: $BAIDU_STATUS)"
              fi
            fi

            echo "--- 检查结束 ---"

            sleep 60

          done
        shell: bash
